In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import Ridge, Lasso ,LinearRegression
from sklearn.preprocessing import StandardScaler 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor 
from sklearn.ensemble import RandomForestRegressor 
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error 
from sklearn.datasets import load_boston 
import warnings
warnings.filterwarnings("ignore")

In [5]:
boston=load_boston()

In [6]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename', 'data_module'])

In [7]:
boston_df = pd.DataFrame(boston.data,columns=boston.feature_names)
boston_df["Price"]=boston.target
boston_df['Price']= boston.target 
boston_df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Price
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2

In [8]:
boston_df.isna().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
Price      0
dtype: int64

In [9]:
boston_df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'Price'],
      dtype='object')

In [10]:
X=boston_df.drop(['Price'],axis=1)
y=boston_df['Price']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=17)

In [12]:
X_train

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
410,51.13580,0.0,18.10,0.0,0.597,5.757,100.0,1.4130,24.0,666.0,20.2,2.60,10.11
76,0.10153,0.0,12.83,0.0,0.437,6.279,74.5,4.0522,5.0,398.0,18.7,373.66,11.97
150,1.65660,0.0,19.58,0.0,0.871,6.122,97.3,1.6180,5.0,403.0,14.7,372.80,14.10
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
455,4.75237,0.0,18.10,0.0,0.713,6.525,86.5,2.4358,24.0,666.0,20.2,50.92,18.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...
406,20.71620,0.0,18.10,0.0,0.659,4.138,100.0,1.1781,24.0,666.0,20.2,370.22,23.34
390,6.96215,0.0,18.10,0.0,0.700,5.713,97.0,1.9265,24.0,666.0,20.2,394.43,17.11
143,4.09740,0.0,19.58,0.0,0.871,5.468,100.0,1.4118,5.0,403.0,14.7,396.90,26.42
241,0.10612,30.0,4.93,0.0,0.428,6.095,65.1,6.3361,6.0,300.0,16.6,394.62,12.40
111,0.10084,0.0,10.01,0.0,0.547,6.715,81.6,2.6775,6.0,432.0,17.8,395.59,10.16

In [13]:
y_test

191    30.5
285    22.0
461    17.7
225    50.0
159    23.3
       ...
498    21.2
189    34.9
3      33.4
356    17.8
86     22.5
Name: Price, Length: 152, dtype: float64

In [14]:
X_test

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
191,0.06911,45.0,3.44,0.0,0.437,6.739,30.8,6.4798,5.0,398.0,15.2,389.71,4.69
285,0.01096,55.0,2.25,0.0,0.389,6.453,31.9,7.3073,1.0,300.0,15.3,394.72,8.23
461,3.69311,0.0,18.10,0.0,0.713,6.376,88.4,2.5671,24.0,666.0,20.2,391.43,14.65
225,0.52693,0.0,6.20,0.0,0.504,8.725,83.0,2.8944,8.0,307.0,17.4,382.00,4.63
159,1.42502,0.0,19.58,0.0,0.871,6.510,100.0,1.7659,5.0,403.0,14.7,364.31,7.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,0.23912,0.0,9.69,0.0,0.585,6.019,65.3,2.4091,6.0,391.0,19.2,396.90,12.92
189,0.08370,45.0,3.44,0.0,0.437,7.185,38.9,4.5667,5.0,398.0,15.2,396.90,5.39
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
356,8.98296,0.0,18.10,1.0,0.770,6.212,97.4,2.1222,24.0,666.0,20.2,377.73,17.60
86,0.05188,0.0,4.49,0.0,0.449,6.015,45.1,4.4272,3.0,247.0,18.5,395.99,12.86

In [15]:
rfr= RandomForestRegressor()

In [16]:
rfr.fit(X_train,y_train)

RandomForestRegressor()

In [17]:
y_pred=rfr.predict(X_test)

In [18]:

rfr.fit(X_train,y_train)
score = rfr.score(X_train,y_train)
print(f"Train Accuarcy for {rfr.__class__.__name__} is {score}") 
score = rfr.score(X_test, y_test) 
print(f"Test Accuarcy for {rfr.__class__.__name__} is {score}") 
print("========================")

Train Accuarcy for RandomForestRegressor is 0.9805995024420213
Test Accuarcy for RandomForestRegressor is 0.9002188410024908
========================

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=17)

In [20]:
from sklearn.linear_model import _linear_loss
dtt=DecisionTreeRegressor(max_depth=3)
dtt.fit(X_train,y_train)
score = dtt.score(X_train,y_train)
print(f"Train Accuarcy for {dtt.__class__.__name__} is {score}") 
score = dtt.score(X_test, y_test) 
print(f"Test Accuarcy for {dtt.__class__.__name__} is {score}") 
print("========================")

Train Accuarcy for DecisionTreeRegressor is 0.8204566080948121
Test Accuarcy for DecisionTreeRegressor is 0.7327456187591291
========================

In [21]:
X=boston_df.drop(['Price'],axis=1)
y=boston_df['Price']

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=17)

In [23]:
lgr = LinearRegression() 
lgr.fit(X_train,y_train)
score = lgr.score(X_train,y_train)
print(f"Train Accuarcy for {lgr.__class__.__name__} is {score}") 
score = lgr.score(X_test, y_test) 
print(f"Test Accuarcy for {lgr.__class__.__name__} is {score}") 
print("========================")

Train Accuarcy for LinearRegression is 0.7295579805153971
Test Accuarcy for LinearRegression is 0.7620882852026805
========================